# -*- coding: utf-8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class LivetexService:
  """
  Сервисы LiveTex


  DIALOG: сервис диалогов. Отвечает за создение диалогов с
    операторами и осуществление переписки.

  VISITOR_DATA: сервис данных посетителя. Отвечает за сопутствующие
    аттрибуты посетителя.

  PRESENCE: сервис присутствия. Отвечает за представление актуальных
    статустов операторов в системе и статической структуры аккаунтов.
  """
  DIALOG = 0
  VISITOR = 1
  PRESENCE = 2
  NOTIFICATION = 3

  _VALUES_TO_NAMES = {
    0: "DIALOG",
    1: "VISITOR",
    2: "PRESENCE",
    3: "NOTIFICATION",
  }

  _NAMES_TO_VALUES = {
    "DIALOG": 0,
    "VISITOR": 1,
    "PRESENCE": 2,
    "NOTIFICATION": 3,
  }

