#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Capabilities:
  CHAT = 0
  LEAD = 1
  CALL = 2
  FILE_TRANSFER = 3

  _VALUES_TO_NAMES = {
    0: "CHAT",
    1: "LEAD",
    2: "CALL",
    3: "FILE_TRANSFER",
  }

  _NAMES_TO_VALUES = {
    "CHAT": 0,
    "LEAD": 1,
    "CALL": 2,
    "FILE_TRANSFER": 3,
  }

