# -*- coding: utf-8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class DeviceType:
  """
  Типы устройств.


  IOS: устройства на платформе iOS.

  ANDROID: устройства на платформа Android.

  WINDOWS_PHONE: устройства на платформе Windows Phone.
  """
  IOS = 0
  ANDROID = 1
  WINDOWS_PHONE = 2

  _VALUES_TO_NAMES = {
    0: "IOS",
    1: "ANDROID",
    2: "WINDOWS_PHONE",
  }

  _NAMES_TO_VALUES = {
    "IOS": 0,
    "ANDROID": 1,
    "WINDOWS_PHONE": 2,
  }

