# -*- coding: utf-8 -*-
#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class VoteType:
  """
  Тип оценки диалога.


  GOOD: диалог понравился.

  BAD: диалог не понравился.
  """
  GOOD = 0
  BAD = 1

  _VALUES_TO_NAMES = {
    0: "GOOD",
    1: "BAD",
  }

  _NAMES_TO_VALUES = {
    "GOOD": 0,
    "BAD": 1,
  }

